name: Tests
on: [ push ]
jobs:
  testing:
    name: Running tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        py-version: [ '3.8', '3.9', '3.10' ]
    steps:
      - name: Setting up github actions runner
        uses: actions/checkout@v3
      - name: Setting up python-${{ matrix.py-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Running unit tests
        run: python -m pytest --import-mode=append tests/
